L = int(input())
N = int(input())
nums = list(map(int, input().split()))
m = -float('inf')
M = -float('inf')
for a in nums:
    b = min(a, L + 1 - a)
    c = max(a, L + 1 - a)
    m = max(m, b)
    M = max(M, c)
print(*[m, M])
